// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrasjoner bruker DIRECT_URL (ikke-poolet Neon-tilkobling) fordi
    // `prisma migrate deploy` tar en Postgres advisory lock som kan tidsavbrytes
    // (P1002) gjennom Neons connection pooler. Faller tilbake til DATABASE_URL
    // lokalt der man typisk ikke har en egen direkte URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
